// Copyright (C) 2026 Textology Labs Ltd. All rights reserved.

/**
 * compose/docker-compose — reference implementation of the `compose.*`
 * namespace using Docker Compose as the orchestration strategy.
 *
 * Pure function of project.yaml. Same input → byte-identical output.
 * No filesystem reads, no timestamps, no randomness.
 *
 * Contract: see ./docker-compose.md. Function signature matches
 * compose.render_topology from .m/providers/provider-interface.md.
 *
 * This module is the source of truth for docker-compose rendering
 * behaviour. The SKILL.md describes the intent; the code here enforces
 * byte-level determinism.
 */

const INDENT = '  ';

/**
 * Main entry point. Returns a list of `{path, content, mode}` entries
 * suitable for the render-topology-artefacts orchestrator to write.
 */
export function render_topology(project) {
  return [
    {
      path: 'docker-compose.yml',
      content: renderDockerCompose(project),
      mode: 0o644,
    },
    {
      path: 'scripts/integration-test.sh',
      content: renderIntegrationTest(project),
      mode: 0o755,
    },
  ];
}

// ---------------------------------------------------------------------------
// docker-compose.yml
// ---------------------------------------------------------------------------

function renderDockerCompose(project) {
  const lines = ['services:'];

  for (let i = 0; i < project.components.length; i++) {
    if (i > 0) lines.push('');
    renderServiceBlock(lines, project.components[i], project);
  }

  if (persistenceEmitted(project)) {
    lines.push('');
    lines.push('volumes:');
    lines.push(`${INDENT}${project.persistence.volume}:`);
  }

  return lines.join('\n') + '\n';
}

function renderServiceBlock(lines, component, project) {
  lines.push(`${INDENT}${component.name}:`);
  lines.push(`${INDENT}${INDENT}build:`);
  lines.push(`${INDENT}${INDENT}${INDENT}context: ${buildContext(component)}`);
  lines.push(`${INDENT}${INDENT}ports:`);
  lines.push(`${INDENT}${INDENT}${INDENT}- "${component.port}:${component.port}"`);

  if (component.role === 'frontend-host') {
    const deps = project.components
      .filter((c) => c.name !== component.name)
      .map((c) => c.name);
    if (deps.length > 0) {
      lines.push(`${INDENT}${INDENT}depends_on:`);
      for (const d of deps) {
        lines.push(`${INDENT}${INDENT}${INDENT}- ${d}`);
      }
    }
  } else if (component.role === 'backend') {
    lines.push(`${INDENT}${INDENT}environment:`);
    lines.push(`${INDENT}${INDENT}${INDENT}- PORT=${component.port}`);
    if (persistenceEmitted(project)) {
      lines.push(`${INDENT}${INDENT}${INDENT}- DB_PATH=${dbPath(project)}`);
      lines.push(`${INDENT}${INDENT}volumes:`);
      lines.push(`${INDENT}${INDENT}${INDENT}- ${project.persistence.volume}:/data`);
    }
  }
}

/**
 * Build context derivation:
 *   embedded   → component.location as-is (already a repo-relative path)
 *   referenced → ../<basename of location> (sibling-on-disk layout,
 *                matching `m clone` and the git clone lines from ci/gitlab)
 */
function buildContext(component) {
  if (component.type === 'embedded') {
    return component.location;
  }
  const parts = component.location.split('/');
  return `../${parts[parts.length - 1]}`;
}

function persistenceEmitted(project) {
  return (
    project.persistence &&
    typeof project.persistence.type === 'string' &&
    typeof project.persistence.volume === 'string' &&
    project.persistence.volume.length > 0
  );
}

/**
 * Persistence-specific container path. Extend here as new types land.
 * Unknown types fall back to the sqlite convention — a concrete path
 * the caller can override, rather than a silent omission.
 */
function dbPath(project) {
  switch (project.persistence.type) {
    case 'sqlite':
    default:
      return `/data/${project.project}.db`;
  }
}

// ---------------------------------------------------------------------------
// scripts/integration-test.sh
// ---------------------------------------------------------------------------

const INTEGRATION_TEST_PREAMBLE = `#!/bin/sh
# Topology aliveness probes.
# Generated by compose.render_topology — do not edit by hand.
# Source of truth: project.yaml.

set -eu

# In GitLab DinD, published ports bind on the 'docker' host, not localhost.
# Locally, override by exporting DOCKER_GATEWAY (e.g. DOCKER_GATEWAY=localhost).
DOCKER_GATEWAY="\${DOCKER_GATEWAY:-docker}"
TIMEOUT="\${TIMEOUT:-60}"

check() {
  name="$1"
  url="$2"
  expected="$3"
  elapsed=0
  until response=$(curl -sf "$url" 2>/dev/null) && echo "$response" | grep -q "$expected"; do
    elapsed=$((elapsed + 2))
    if [ "$elapsed" -ge "$TIMEOUT" ]; then
      echo "FAIL: $name — $url did not contain '$expected' within \${TIMEOUT}s"
      return 1
    fi
    sleep 2
  done
  echo "✓ $name"
}
`;

const INTEGRATION_TEST_EPILOGUE = `
echo ""
echo "All topology aliveness probes passed."
`;

function renderIntegrationTest(project) {
  const probeLines = ['', '# Infrastructure baseline — topology aliveness probes'];
  probeLines.push('echo "Infrastructure baseline — topology aliveness probes:"');
  for (const c of project.components) {
    probeLines.push(renderProbeLine(c));
  }
  probeLines.push('');

  return (
    INTEGRATION_TEST_PREAMBLE
    + probeLines.join('\n')
    + INTEGRATION_TEST_EPILOGUE
  );
}

function renderProbeLine(component) {
  const gateway = '${DOCKER_GATEWAY}';
  switch (component.role) {
    case 'frontend-host':
      return `check "${component.name} renders" "http://${gateway}:${component.port}" "app-shell"`;
    case 'frontend':
      return `check "${component.name} remoteEntry.js served" "http://${gateway}:${component.port}/remoteEntry.js" "webpackChunk"`;
    case 'backend':
      return `check "${component.name} health" "http://${gateway}:${component.port}/health" "ok"`;
    default:
      // Unknown role — emit a generic health probe so the script still runs.
      return `check "${component.name} alive" "http://${gateway}:${component.port}/" ""`;
  }
}
